# -*- coding: utf-8 -*-
"""Resume Bullet Point Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbC5IufJFpDIfXCHpnZzqTBGd7axbABg
"""

!pip install --upgrade openai

!pip install streamlit python-dotenv openai==1.12.0 > /dev/null

app_code = """
import streamlit as st
import requests
import json

# ✅ Azure OpenAI deployment settings
AZURE_ENDPOINT = "https://openai-mochi.services.ai.azure.com/"
AZURE_KEY = "YOUR KEY HERE"
DEPLOYMENT = "gpt-35-turbo"
API_VERSION = "2024-02-01"

headers = {
    "Content-Type": "application/json",
    "api-key": AZURE_KEY
}

def generate_bullets(job_title, skills):
    prompt = f\"\"\"
Generate 6 strong resume bullet points for a {job_title}.
Include these skills: {skills}.
Make them achievement-focused, start with action verbs, quantify if possible.
\"\"\"

    body = {
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.3
    }

    url = f"{AZURE_ENDPOINT}openai/deployments/{DEPLOYMENT}/chat/completions?api-version={API_VERSION}"
    response = requests.post(url, headers=headers, json=body)
    return response.json()["choices"][0]["message"]["content"]


st.set_page_config(page_title="Resume Builder", page_icon="💼")
st.title("💼 AI Resume Bullet Point Generator")

with st.form("resume"):
    job_title = st.text_input("Target Job Title")
    skills = st.text_area("Skills (comma-separated)")
    submitted = st.form_submit_button("Generate ✅")

if submitted:
    if not job_title or not skills:
        st.error("Please fill out all fields.")
    else:
        with st.spinner("Creating bullet points..."):
            bullets = generate_bullets(job_title, skills)
        st.subheader("✅ Your Bullet Points")
        st.write(bullets)
"""

with open("resume_app.py", "w") as f:
    f.write(app_code)

!pkill -f streamlit || true
!fuser -k 8501/tcp || true
!streamlit run resume_app.py --server.port 8501 --server.headless true &>/dev/null&

import subprocess, time, re
!wget -q -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared

p = subprocess.Popen(
    ["./cloudflared", "tunnel", "--url", "http://localhost:8501", "--no-autoupdate"],
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
)

url = None
for _ in range(200):
    line = p.stdout.readline()
    if "trycloudflare.com" in line:
        match = re.search(r"https://[^\s]+", line)
        if match:
            url = match.group(0)
            break

print("Resume App URL:", url if url else "Starting... wait 10s")

